auto_download_pdfs|DAILY|11:50|/home/sidd/project/smart-job-scanner-v2|/home/sidd/project/smart-job-scanner-v2/4_env/bin/python /home/sidd/project/smart-job-scanner-v2/src/downloader/newspaper_downloader.py|yes

force_pipeline|DAILY|23:30|/home/sidd/project/smart-job-scanner-v2|/bin/bash -lc "/home/sidd/project/smart-job-scanner-v2/scripts/run_pipeline.sh --force"|yes
